# Generated by Django 5.2.13 on 2026-04-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntrinsicAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(help_text='e.g., DANGCEM, MTNN', max_length=15)),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('operating_profit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('finance_income', models.DecimalField(decimal_places=2, max_digits=20)),
                ('one_off_gains', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('tax_expenses', models.DecimalField(decimal_places=2, max_digits=20)),
                ('profit_after_tax', models.DecimalField(decimal_places=2, max_digits=20)),
                ('finance_cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_equity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_debt', models.DecimalField(decimal_places=2, max_digits=20)),
                ('free_cash_flow', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_os', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Total Shares Outstanding')),
                ('current_sp', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Current Share Price')),
                ('total_div', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Total Dividend Paid')),
                ('current_inf', models.DecimalField(decimal_places=2, default=15.1, max_digits=5, verbose_name='Inflation %')),
                ('ai_commentary', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Intrinsic Analyses',
            },
        ),
    ]
