# Generated by Django 5.2.13 on 2026-04-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngx_valuation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intrinsicanalysis',
            name='finance_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='intrinsicanalysis',
            name='free_cash_flow',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='intrinsicanalysis',
            name='one_off_gains',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='intrinsicanalysis',
            name='total_debt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
