# Generated by Django 5.2.13 on 2026-04-24 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngx_valuation', '0002_alter_intrinsicanalysis_finance_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intrinsicanalysis',
            name='finance_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
