# Generated by Django 5.2.13 on 2026-04-24 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngx_valuation', '0003_alter_intrinsicanalysis_finance_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intrinsicanalysis',
            name='total_div',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Total Dividend Paid'),
        ),
    ]
