# Generated by Django 5.2.13 on 2026-05-27 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngx_valuation', '0004_alter_intrinsicanalysis_total_div'),
    ]

    operations = [
        migrations.AddField(
            model_name='intrinsicanalysis',
            name='report_quarter',
            field=models.CharField(choices=[('Q1', 'Q1 (First Quarter - 3 Months)'), ('Q2', 'Q2 / H1 (Half Year - 6 Months Cumulative)'), ('Q3', 'Q3 (Nine Months - 9 Months Cumulative)'), ('FY', 'FY (Full Year - 12 Months)')], default='Q1', max_length=2, verbose_name='Reporting Period'),
        ),
    ]
