# Generated by Django 5.2.13 on 2026-09-27 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngx_valuation', '0005_intrinsicanalysis_report_quarter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intrinsicanalysis',
            options={'ordering': ['-analysis_date'], 'verbose_name': 'Intrinsic Analysis', 'verbose_name_plural': 'Intrinsic Analyses'},
        ),
        migrations.AddField(
            model_name='intrinsicanalysis',
            name='sector',
            field=models.CharField(choices=[('NON_BANK', 'Non-Banking / Industrial / Commercial'), ('BANK', 'Banking / Financial Institution')], default='NON_BANK', help_text='Determines whether cash flow metrics like FCF apply.', max_length=10, verbose_name='Sector Type'),
        ),
        migrations.AlterField(
            model_name='intrinsicanalysis',
            name='ai_commentary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='intrinsicanalysis',
            name='current_sp',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Current Share Price (₦)'),
        ),
        migrations.AlterField(
            model_name='intrinsicanalysis',
            name='finance_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='intrinsicanalysis',
            name='finance_income',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='intrinsicanalysis',
            name='free_cash_flow',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank or set 0 for banking sector records.', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='intrinsicanalysis',
            name='one_off_gains',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Non-recurring income to subtract from operating profit.', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='intrinsicanalysis',
            name='ticker',
            field=models.CharField(db_index=True, help_text='e.g., DANGCEM, MTNN, UBA, GTCO', max_length=15),
        ),
        migrations.AlterField(
            model_name='intrinsicanalysis',
            name='total_debt',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='intrinsicanalysis',
            name='total_div',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Total Dividend Paid (₦)'),
        ),
        migrations.AlterField(
            model_name='intrinsicanalysis',
            name='total_os',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Total Shares Outstanding (Millions)'),
        ),
    ]
